// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzSkNkd1kKYPEKMiMqH4IXtz13JApR40',
    appId: '1:663204079303:web:ac27ce417a321602a040e2',
    messagingSenderId: '663204079303',
    projectId: 'fitgate-iot',
    authDomain: 'fitgate-iot.firebaseapp.com',
    storageBucket: 'fitgate-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf9dibi-PBj8lOEsuuBbx2OIdBaEoOrHA',
    appId: '1:663204079303:android:ab5b198957c8e82aa040e2',
    messagingSenderId: '663204079303',
    projectId: 'fitgate-iot',
    storageBucket: 'fitgate-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3tbv-v5l9dZuyM_a9JHOKC65StNLJsbM',
    appId: '1:663204079303:ios:b20382077a714efba040e2',
    messagingSenderId: '663204079303',
    projectId: 'fitgate-iot',
    storageBucket: 'fitgate-iot.firebasestorage.app',
    iosBundleId: 'com.example.fitgateClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3tbv-v5l9dZuyM_a9JHOKC65StNLJsbM',
    appId: '1:663204079303:ios:b20382077a714efba040e2',
    messagingSenderId: '663204079303',
    projectId: 'fitgate-iot',
    storageBucket: 'fitgate-iot.firebasestorage.app',
    iosBundleId: 'com.example.fitgateClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzSkNkd1kKYPEKMiMqH4IXtz13JApR40',
    appId: '1:663204079303:web:e4adb0e425b60993a040e2',
    messagingSenderId: '663204079303',
    projectId: 'fitgate-iot',
    authDomain: 'fitgate-iot.firebaseapp.com',
    storageBucket: 'fitgate-iot.firebasestorage.app',
  );
}
